import { defineConfig } from "astro/config";
import sveltia from "astro-loader-sveltia-cms";

export default defineConfig({
  site: "https://paulaferi.github.io",
  base: "/feri-informatika-web",
  vite: {
    resolve: {
      alias: {
        "@": "/src",
      },
    },
  },
  integrations: [
    sveltia({
      config: {
        backend: {
          name: "github",
          repo: "paulaferi/feri-informatika-web",
          branch: "main",
        },
        media_folder: "/src/assets/media",
        public_folder: "@/assets/media",
        collections: [
          {
            name: "laboratories",
            label: "Laboratories",
            folder: "src/content/laboratories",
            create: true,
            slug: "{{slug}}",
            fields: [
              { name: "name", label: "Laboratory Name", widget: "string" },
              { name: "acronym", label: "Acronym", widget: "string", required: false },
              { name: "description", label: "Description", widget: "text", required: false },
              { name: "researchAreas", label: "Research Areas", widget: "list", required: false,
                field: { name: "area", label: "Area", widget: "string" } },
              { name: "members", label: "Staff Members (slugs)", widget: "list",required: false,
                field: { name: "member", label: "Staff slug", widget: "string" } },
              { name: "externalUrl", label: "External URL", widget: "string", required: false },
              { name: "body", label: "Extended description", widget: "markdown", required: false },
            ],
          },
          {
            name: "interestGroups",
            label: "Interest Groups",
            folder: "src/content/interest-groups",
            create: true,
            slug: "{{slug}}",
            fields: [
              { name: "name", label: "Group Name", widget: "string" },
              { name: "description", label: "Brief Description", widget: "text" },
              { name: "url", label: "External Link", widget: "string", required: false },
              { name: "body", label: "Full description", widget: "markdown", required: false },
            ],
          },
          {
            name: "staff",
            label: "Staff",
            folder: "src/content/staff",
            create: true,
            slug: "{{slug}}",
            identifier_field: "name",
            fields: [
              { name: "name", label: "Full Name", widget: "string" },
              { name: "photo", label: "Photo", widget: "image", required: false },
              { name: "title", label: "Title (e.g. Assoc. Prof., PhD.)", widget: "string", required: false },
              { name: "role", label: "Position / Role", widget: "string" },
              {
                name: "section",
                label: "Sekcija",
                widget: "select",
                options: [
                  { label: "Predstojnik inštituta",      value: "predstojnik" },
                  { label: "Profesorji in predavatelji", value: "profesorji" },
                  { label: "Asistenti in raziskovalci",  value: "asistenti" },
                  { label: "Tehnično osebje",            value: "tehnicno" },
                  { label: "Prejšnji člani",             value: "prejsnji" },
                ],
                default: "profesorji",
                required: false,
              },
              { name: "email", label: "E-mail", widget: "string", required: false },
              { name: "phone", label: "Telephone", widget: "string", required: false },
              { name: "office", label: "Room", widget: "string", required: false },
              { name: "contactHours", label: "Contact Hours (URL)", widget: "string", required: false },
              { name: "linkedin", label: "LinkedIn Profile (URL)", widget: "string", required: false },
              { name: "cobiss", label: "Publications — COBISS URL", widget: "string", required: false },
              { name: "researchTopics", label: "Main Research Topics", widget: "markdown", required: false },
              { name: "publications", label: "List of Selected Publications", widget: "markdown", required: false },
              { name: "cv", label: "CV", widget: "markdown", required: false },
              { name: "teaching", label: "Teaching", widget: "markdown", required: false },
              { name: "projects", label: "Project Leader / Coordinator", widget: "markdown", required: false },
              { name: "editorial", label: "Editor", widget: "markdown", required: false },
              { name: "awards", label: "Awards", widget: "markdown", required: false },
              { name: "conferenceOrg", label: "Conference Organization", widget: "markdown", required: false },
              { name: "projectsCollab", label: "Projects Collaboration", widget: "markdown", required: false },
              { name: "reviewerFor", label: "Reviewer for Journals", widget: "markdown", required: false },
              { name: "certificates", label: "Certificates", widget: "markdown", required: false },
              { name: "zaposlitev",                      label: "Zaposlitev",                           widget: "markdown", required: false },
              { name: "kratkaBiografija",               label: "Kratka biografija",                    widget: "markdown", required: false },
              { name: "področjaRaziskovalnegaDela",     label: "Področja raziskovalnega dela",          widget: "markdown", required: false },
              { name: "glavnaInteresnaInRaziskovalnaPodrocja", label: "Glavna interesna in raziskovalna področja", widget: "markdown", required: false },
              { name: "raziskovalnoDelo",               label: "Raziskovalno delo",                    widget: "markdown", required: false },
              { name: "delovneIzkusnje",                label: "Delovne izkušnje",                     widget: "markdown", required: false },
              { name: "izobrazevanjeVTujini",           label: "Izobraževanja v tujini",               widget: "markdown", required: false },
              { name: "studijInRaziskovanjeVTujini",    label: "Študij in raziskovanje v tujini",      widget: "markdown", required: false },
              { name: "studijskeIzmenjave",             label: "Študijske izmenjave",                  widget: "markdown", required: false },
              { name: "izmenjave",                      label: "Izmenjave",                            widget: "markdown", required: false },
              { name: "vabljenaPredavanja",             label: "Vabljena predavanja",                  widget: "markdown", required: false },
              { name: "delavniceInVabljenaPredavanja",  label: "Delavnice in vabljena predavanja",     widget: "markdown", required: false },
              { name: "izvedbaDelavnic",                label: "Izvedba delavnic",                     widget: "markdown", required: false },
              { name: "posebnaVabila",                  label: "Posebna vabila",                       widget: "markdown", required: false },
              { name: "organiziranjeInVodenjeKonferenc", label: "Organiziranje in vodenje konferenc",  widget: "markdown", required: false },
              { name: "sodelovanjePriKonferencah",      label: "Sodelovanje pri konferencah",          widget: "markdown", required: false },
              { name: "konferencneAktivnosti",          label: "Konferenčne aktivnosti",               widget: "markdown", required: false },
              { name: "projektneAktivnosti",            label: "Projektne aktivnosti",                 widget: "markdown", required: false },
              { name: "vodjaKoordinatorProjekta",       label: "Vodja/Koordinator projekta",           widget: "markdown", required: false },
              { name: "sodelovanjePriProjektu",         label: "Sodelovanje pri projektu",             widget: "markdown", required: false },
              { name: "recenzijskeInUredniskeAktivnosti", label: "Recenzijske in uredniške aktivnosti", widget: "markdown", required: false },
              { name: "urednistvo",                     label: "Uredništvo",                           widget: "markdown", required: false },
              { name: "pedagoskaDejavnost",             label: "Pedagoška dejavnost",                  widget: "markdown", required: false },
              { name: "mentorstva",                     label: "Mentorstva",                           widget: "markdown", required: false },
              { name: "clanstvo",                       label: "Članstvo",                             widget: "markdown", required: false },
              { name: "clanicaOdborov",                 label: "Članica odborov",                      widget: "markdown", required: false },
              { name: "polozaji",                       label: "Položaji",                             widget: "markdown", required: false },
              { name: "sodelovanjeVDelovihSkupinah",    label: "Sodelovanje v delovnih skupinah",      widget: "markdown", required: false },
              { name: "mednarodnaDejavnost",            label: "Mednarodna dejavnost",                 widget: "markdown", required: false },
              { name: "vMedijih",                       label: "V medijih",                            widget: "markdown", required: false },
            ],
          },
          {
            name: "projects",
            label: "Research Projects",
            folder: "src/content/projects",
            create: true,
            identifier_field: "title",
            slug: "{{slug}}",
            fields: [
              { name: "title", label: "Project Title", widget: "string" },
              { name: "status", label: "Status", widget: "select",
                options: ["active", "past"] },
              { name: "description", label: "Short Description", widget: "text" },
              { name: "startYear", label: "Start Year", widget: "number" },
              { name: "endYear", label: "End Year", widget: "number", required: false },
              { name: "funder", label: "Funding Body", widget: "string", required: false },
              { name: "principalInvestigator", label: "Principal Investigator", widget: "string", required: false },
              { name: "newsLink", label: "Link to related news (manual)", widget: "string", required: false },
              { name: "body", label: "Full Description & Details", widget: "markdown", required: false },
            ],
          },
          {
            name: "ethicsOpinions",
            label: "Ethics Committee — Opinions",
            folder: "src/content/ethics-opinions",
            create: true,
            slug: "{{slug}}",
            fields: [
              { name: "date", label: "Date", widget: "datetime" },
              { name: "research", label: "Research Title", widget: "string" },
              { name: "researchers", label: "Researchers", widget: "string" },
              { name: "decision", label: "Decision / Opinion", widget: "text", required: false },
            ],
          },
          {
            name: "studyProgrammes",
            label: "Study Programmes",
            folder: "src/content/study-programmes",
            create: true,
            slug: "{{slug}}",
            fields: [
              { name: "title", label: "Programme Title", widget: "string" },
              { name: "type", label: "Type", widget: "select",
                options: ["IPT", "ITK", "Bachelor", "Master", "PhD"] },
              { name: "duration", label: "Duration (years)", widget: "number" },
              { name: "ects", label: "ECTS Credits", widget: "number" },
              { name: "scope", label: "Scope", widget: "string", required: false },
              { name: "externalUrl", label: "Link to moja.um.si", widget: "string", required: false },
              { name: "body", label: "Curriculum & General Info", widget: "markdown", required: false },
            ],
          },
          {
            name: "studentProjects",
            label: "Student Projects",
            folder: "src/content/student-projects",
            create: true,
            slug: "{{slug}}",
            fields: [
              { name: "title", label: "Project Title", widget: "string" },
              { name: "student", label: "Student Name(s)", widget: "string" },
              { name: "year", label: "Year", widget: "number" },
              { name: "description", label: "Short Description", widget: "text" },
              { name: "externalUrl", label: "Link to praktik.um.si", widget: "string", required: false },
              { name: "body", label: "Full Details", widget: "markdown", required: false },
            ],
          },
          {
            name: "conferences",
            label: "Conferences",
            folder: "src/content/conferences",
            create: true,
            slug: "{{slug}}",
            fields: [
              { name: "name", label: "Conference Name", widget: "string" },
              { name: "acronym", label: "Acronym", widget: "string", required: false },
              { name: "description", label: "Description", widget: "text" },
              { name: "date", label: "Date", widget: "datetime", required: false },
              { name: "location", label: "Location", widget: "string", required: false },
              { name: "url", label: "Conference Website", widget: "string", required: false },
              { name: "body", label: "Full Details", widget: "markdown", required: false },
            ],
          },
          {
            name: "industryPartners",
            label: "Industry Partners",
            folder: "src/content/industry-partners",
            create: true,
            slug: "{{slug}}",
            fields: [
              { name: "name", label: "Organisation Name", widget: "string" },
              { name: "description", label: "Collaboration Description", widget: "text" },
              { name: "logo", label: "Logo", widget: "image", required: false },
              { name: "url", label: "Website", widget: "string", required: false },
            ],
          },
          {
            name: "achievements",
            label: "Achievements & Activities",
            folder: "src/content/achievements",
            create: true,
            slug: "{{slug}}",
            identifier_field: "title",
            fields: [
              { name: "title", label: "Title", widget: "string" },
              { name: "subtitle", label: "Subtitle", widget: "string", required: false },
              { name: "date", label: "Date", widget: "datetime" },
              { name: "tags", label: "Tags", widget: "select", multiple: true,
                options: ["student", "conference", "scientific", "professional",
                          "project", "awards", "interest-groups"] },
              { name: "coverImage", label: "Cover Image", widget: "image", required: false },
              { name: "images", label: "Additional Images", widget: "list", required: false,
                field: { name: "image", label: "Image", widget: "image" } },
              { name: "body", label: "Full Text", widget: "markdown" },
            ],
          },
          {
            name: "news",
            label: "News",
            folder: "src/content/news",
            create: true,
            slug: "{{year}}-{{month}}-{{day}}-{{slug}}",
            fields: [
              { name: "title", label: "Title", widget: "string" },
              { name: "date", label: "Date", widget: "datetime" },
              { name: "tags", label: "Tags", widget: "select", multiple: true,
                options: ["student", "conference", "scientific", "professional",
                          "project", "awards", "interest-groups"] },
              { name: "summary", label: "Summary", widget: "text" },
              { name: "coverImage", label: "Cover Image", widget: "image", required: false },
              { name: "images", label: "Additional Images", widget: "list", required: false,
                field: { name: "image", label: "Image", widget: "image" } },
              { name: "body", label: "Full Content", widget: "markdown" },
            ],
          },
          {
            name: "siteConfig",
            label: "Site Configuration",
            files: [
              {
                name: "highlighted",
                label: "Highlighted Content",
                file: "src/content/config/highlighted.json",
                fields: [
                  {
                    name: "news",
                    label: "Highlighted News — select 2/3 news to feature on the homepage",
                    widget: "relation",
                    collection: "news",
                    search_fields: ["title"],
                    value_field: "{{slug}}",
                    display_fields: ["title"],
                    multiple: true,
                    min: 2,
                    max: 3,
                  },
                  {
                    name: "achievements",
                    label: "Highlighted Achievements — selecciona 2 o 3",
                    widget: "relation",
                    collection: "achievements",
                    search_fields: ["title"],
                    value_field: "{{slug}}",
                    display_fields: ["title"],
                    multiple: true,
                    min: 2,
                    max: 3,
                  },
                  {
                    name: "projects",
                    label: "Highlighted Projects — selecciona 2 o 3",
                    widget: "relation",
                    collection: "projects",
                    search_fields: ["title"],
                    value_field: "{{slug}}",
                    display_fields: ["title"],
                    multiple: true,
                    min: 2,
                    max: 3,
                  },
                ]
              }
            ]
          },
        ],
      },
    }),
  ],
});