import { defineConfig } from "astro/config";
import sveltia from "astro-loader-sveltia-cms";

export default defineConfig({
  site: "https://paulaferi.github.io",
  base: "/feri-informatika-web",
  i18n: {
    defaultLocale: "sl",
    locales: ["sl", "en"],
    routing: {
      prefixDefaultLocale: false,
    },
  },
  vite: {
    resolve: {
      alias: {
        "@": "/src",
      },
    },
  },
  integrations: [
    sveltia({
      config: {
        backend: {
          name: "github",
          repo: "paulaferi/feri-informatika-web",
          branch: "main",
        },
        media_folder: "/src/assets/media",
        public_folder: "@/assets/media",
        locale: "sl",
        collections: [
          {
            name: "laboratories",
            label: "Laboratoriji",
            folder: "src/content/laboratories",
            create: true,
            slug: "{{slug}}",
            fields: [
              { name: "name", label: "Ime laboratorija", widget: "string" },
              { name: "acronym", label: "Kratica", widget: "string", required: false },
              { name: "description", label: "Opis", widget: "text", required: false },
              { name: "researchAreas", label: "Raziskovalna področja", widget: "list", required: false,
                field: { name: "area", label: "Področje", widget: "string" } },
              { name: "members", label: "Člani osebja (slugs)", widget: "list", required: false,
                field: { name: "member", label: "Slug osebja", widget: "string" } },
              { name: "externalUrl", label: "Zunanja povezava", widget: "string", required: false },
              { name: "body", label: "Razširjen opis", widget: "markdown", required: false },
            ],
          },
          {
            name: "interestGroups",
            label: "Interesne skupine",
            folder: "src/content/interest-groups",
            create: true,
            slug: "{{slug}}",
            fields: [
              { name: "name", label: "Ime skupine", widget: "string" },
              { name: "description", label: "Kratek opis", widget: "text" },
              { name: "url", label: "Zunanja povezava", widget: "string", required: false },
              { name: "body", label: "Celoten opis", widget: "markdown", required: false },
            ],
          },
          {
            name: "staff",
            label: "Osebje",
            folder: "src/content/staff",
            create: true,
            slug: "{{slug}}",
            identifier_field: "name",
            fields: [
              { name: "name", label: "Polno ime", widget: "string" },
              { name: "photo", label: "Fotografija", widget: "image", required: false },
              { name: "title", label: "Naziv (npr. doc. dr., prof. dr.)", widget: "string", required: false },
              { name: "role", label: "Položaj / vloga", widget: "string" },
              {
                name: "section",
                label: "Sekcija",
                widget: "select",
                options: [
                  { label: "Predstojnik inštituta",      value: "predstojnik" },
                  { label: "Profesorji in predavatelji", value: "profesorji" },
                  { label: "Asistenti in raziskovalci",  value: "asistenti" },
                  { label: "Tehnično osebje",            value: "tehnicno" },
                  { label: "Prejšnji člani",             value: "prejsnji" },
                ],
                default: "profesorji",
                required: false,
              },
              { name: "email", label: "E-mail", widget: "string", required: false },
              { name: "phone", label: "Telefon", widget: "string", required: false },
              { name: "office", label: "Pisarna", widget: "string", required: false },
              { name: "contactHours", label: "Govorilne ure (URL)", widget: "string", required: false },
              { name: "linkedin", label: "LinkedIn profil (URL)", widget: "string", required: false },
              { name: "cobiss", label: "Publikacije — COBISS URL", widget: "string", required: false },
              { name: "researchTopics", label: "Glavna raziskovalna področja", widget: "markdown", required: false },
              { name: "publications", label: "Seznam izbranih publikacij", widget: "markdown", required: false },
              { name: "cv", label: "CV", widget: "markdown", required: false },
              { name: "teaching", label: "Pedagoška dejavnost", widget: "markdown", required: false },
              { name: "projects", label: "Vodja / koordinator projekta", widget: "markdown", required: false },
              { name: "editorial", label: "Urednik", widget: "markdown", required: false },
              { name: "awards", label: "Nagrade", widget: "markdown", required: false },
              { name: "conferenceOrg", label: "Organizacija konferenc", widget: "markdown", required: false },
              { name: "projectsCollab", label: "Sodelovanje pri projektih", widget: "markdown", required: false },
              { name: "reviewerFor", label: "Recenzent za revije", widget: "markdown", required: false },
              { name: "certificates", label: "Certifikati", widget: "markdown", required: false },
              { name: "zaposlitev",                      label: "Zaposlitev",                           widget: "markdown", required: false },
              { name: "kratkaBiografija",               label: "Kratka biografija",                    widget: "markdown", required: false },
              { name: "področjaRaziskovalnegaDela",     label: "Področja raziskovalnega dela",          widget: "markdown", required: false },
              { name: "glavnaInteresnaInRaziskovalnaPodrocja", label: "Glavna interesna in raziskovalna področja", widget: "markdown", required: false },
              { name: "raziskovalnoDelo",               label: "Raziskovalno delo",                    widget: "markdown", required: false },
              { name: "delovneIzkusnje",                label: "Delovne izkušnje",                     widget: "markdown", required: false },
              { name: "izobrazevanjeVTujini",           label: "Izobraževanja v tujini",               widget: "markdown", required: false },
              { name: "studijInRaziskovanjeVTujini",    label: "Študij in raziskovanje v tujini",      widget: "markdown", required: false },
              { name: "studijskeIzmenjave",             label: "Študijske izmenjave",                  widget: "markdown", required: false },
              { name: "izmenjave",                      label: "Izmenjave",                            widget: "markdown", required: false },
              { name: "vabljenaPredavanja",             label: "Vabljena predavanja",                  widget: "markdown", required: false },
              { name: "delavniceInVabljenaPredavanja",  label: "Delavnice in vabljena predavanja",     widget: "markdown", required: false },
              { name: "izvedbaDelavnic",                label: "Izvedba delavnic",                     widget: "markdown", required: false },
              { name: "posebnaVabila",                  label: "Posebna vabila",                       widget: "markdown", required: false },
              { name: "organiziranjeInVodenjeKonferenc", label: "Organiziranje in vodenje konferenc",  widget: "markdown", required: false },
              { name: "sodelovanjePriKonferencah",      label: "Sodelovanje pri konferencah",          widget: "markdown", required: false },
              { name: "konferencneAktivnosti",          label: "Konferenčne aktivnosti",               widget: "markdown", required: false },
              { name: "projektneAktivnosti",            label: "Projektne aktivnosti",                 widget: "markdown", required: false },
              { name: "vodjaKoordinatorProjekta",       label: "Vodja/Koordinator projekta",           widget: "markdown", required: false },
              { name: "sodelovanjePriProjektu",         label: "Sodelovanje pri projektu",             widget: "markdown", required: false },
              { name: "recenzijskeInUredniskeAktivnosti", label: "Recenzijske in uredniške aktivnosti", widget: "markdown", required: false },
              { name: "urednistvo",                     label: "Uredništvo",                           widget: "markdown", required: false },
              { name: "pedagoskaDejavnost",             label: "Pedagoška dejavnost",                  widget: "markdown", required: false },
              { name: "mentorstva",                     label: "Mentorstva",                           widget: "markdown", required: false },
              { name: "clanstvo",                       label: "Članstvo",                             widget: "markdown", required: false },
              { name: "clanicaOdborov",                 label: "Članica odborov",                      widget: "markdown", required: false },
              { name: "polozaji",                       label: "Položaji",                             widget: "markdown", required: false },
              { name: "sodelovanjeVDelovihSkupinah",    label: "Sodelovanje v delovnih skupinah",      widget: "markdown", required: false },
              { name: "mednarodnaDejavnost",            label: "Mednarodna dejavnost",                 widget: "markdown", required: false },
              { name: "vMedijih",                       label: "V medijih",                            widget: "markdown", required: false },
            ],
          },
          {
            name: "projects",
            label: "Raziskovalni projekti",
            folder: "src/content/projects",
            create: true,
            identifier_field: "title",
            slug: "{{slug}}",
            fields: [
              { name: "title", label: "Naslov projekta", widget: "string" },
              { name: "status", label: "Status", widget: "select",
                options: ["active", "past"] },
              { name: "description", label: "Kratek opis", widget: "text" },
              { name: "startYear", label: "Leto začetka", widget: "number" },
              { name: "endYear", label: "Leto zaključka", widget: "number", required: false },
              { name: "funder", label: "Financerji", widget: "string", required: false },
              { name: "principalInvestigator", label: "Vodja projekta", widget: "string", required: false },
              { name: "newsLink", label: "Povezava do novic (ročno)", widget: "string", required: false },
              { name: "body", label: "Celoten opis in podrobnosti", widget: "markdown", required: false },
            ],
          },
          {
            name: "ethicsOpinions",
            label: "Etična komisija — Mnenja",
            folder: "src/content/ethics-opinions",
            create: true,
            slug: "{{slug}}",
            fields: [
              { name: "date", label: "Datum", widget: "datetime" },
              { name: "research", label: "Naslov raziskave", widget: "string" },
              { name: "researchers", label: "Raziskovalci", widget: "string" },
              { name: "decision", label: "Odločitev / mnenje", widget: "text", required: false },
            ],
          },
          {
            name: "studyProgrammes",
            label: "Študijski programi",
            folder: "src/content/study-programmes",
            create: true,
            slug: "{{slug}}",
            fields: [
              { name: "title", label: "Naziv programa", widget: "string" },
              { name: "type", label: "Vrsta", widget: "select",
                options: ["IPT", "ITK", "Bachelor", "Master", "PhD"] },
              { name: "duration", label: "Trajanje (leta)", widget: "number" },
              { name: "ects", label: "ECTS krediti", widget: "number" },
              { name: "scope", label: "Obseg", widget: "string", required: false },
              { name: "externalUrl", label: "Povezava na moja.um.si", widget: "string", required: false },
              { name: "body", label: "Učni načrt in splošne informacije", widget: "markdown", required: false },
            ],
          },
          {
            name: "studentProjects",
            label: "Študentski projekti",
            folder: "src/content/student-projects",
            create: true,
            slug: "{{slug}}",
            fields: [
              { name: "title", label: "Naslov projekta", widget: "string" },
              { name: "student", label: "Ime(na) študenta", widget: "string" },
              { name: "year", label: "Leto", widget: "number" },
              { name: "description", label: "Kratek opis", widget: "text" },
              { name: "externalUrl", label: "Povezava na praktik.um.si", widget: "string", required: false },
              { name: "body", label: "Podrobnosti", widget: "markdown", required: false },
            ],
          },
          {
            name: "conferences",
            label: "Konference",
            folder: "src/content/conferences",
            create: true,
            slug: "{{slug}}",
            fields: [
              { name: "name", label: "Ime konference", widget: "string" },
              { name: "acronym", label: "Kratica", widget: "string", required: false },
              { name: "description", label: "Opis", widget: "text" },
              { name: "date", label: "Datum", widget: "datetime", required: false },
              { name: "location", label: "Kraj", widget: "string", required: false },
              { name: "url", label: "Spletna stran konference", widget: "string", required: false },
              { name: "body", label: "Podrobnosti", widget: "markdown", required: false },
            ],
          },
          {
            name: "industryPartners",
            label: "Industrijski partnerji",
            folder: "src/content/industry-partners",
            create: true,
            slug: "{{slug}}",
            fields: [
              { name: "name", label: "Ime organizacije", widget: "string" },
              { name: "description", label: "Opis sodelovanja", widget: "text" },
              { name: "logo", label: "Logotip", widget: "image", required: false },
              { name: "url", label: "Spletna stran", widget: "string", required: false },
            ],
          },
          {
            name: "achievements",
            label: "Dosežki in aktivnosti",
            folder: "src/content/achievements",
            create: true,
            slug: "{{slug}}",
            identifier_field: "title",
            fields: [
              { name: "title", label: "Naslov", widget: "string" },
              { name: "subtitle", label: "Podnaslov", widget: "string", required: false },
              { name: "date", label: "Datum", widget: "datetime" },
              { name: "tags", label: "Oznake", widget: "select", multiple: true,
                options: ["student", "conference", "scientific", "professional",
                          "project", "awards", "interest-groups"] },
              { name: "coverImage", label: "Naslovna slika", widget: "image", required: false },
              { name: "images", label: "Dodatne slike", widget: "list", required: false,
                field: { name: "image", label: "Slika", widget: "image" } },
              { name: "body", label: "Celotno besedilo", widget: "markdown" },
              {
                name: "videos",
                label: "Videoposnetki",
                widget: "list",
                required: false,
                field: { name: "video", label: "Video (ruta o URL)", widget: "string" },
              },
            ],
          },
          {
            name: "news",
            label: "Novice",
            folder: "src/content/news",
            create: true,
            slug: "{{year}}-{{month}}-{{day}}-{{slug}}",
            fields: [
              { name: "title", label: "Naslov", widget: "string" },
              { name: "date", label: "Datum", widget: "datetime" },
              { name: "tags", label: "Oznake", widget: "select", multiple: true,
                options: ["student", "conference", "scientific", "professional",
                          "project", "awards", "interest-groups"] },
              { name: "summary", label: "Povzetek", widget: "text" },
              { name: "coverImage", label: "Naslovna slika", widget: "image", required: false },
              { name: "images", label: "Dodatne slike", widget: "list", required: false,
                field: { name: "image", label: "Slika", widget: "image" } },
              { name: "body", label: "Celotna vsebina", widget: "markdown" },
            ],
          },
          {
            name: "siteConfig",
            label: "Konfiguracija strani",
            files: [
              {
                name: "highlighted",
                label: "Izpostavljena vsebina",
                file: "src/content/config/highlighted.json",
                fields: [
                  {
                    name: "news",
                    label: "Izpostavljene novice — izberi 2 ali 3 novice za prikaz na naslovnici",
                    widget: "relation",
                    collection: "news",
                    search_fields: ["title"],
                    value_field: "{{slug}}",
                    display_fields: ["title"],
                    multiple: true,
                    min: 2,
                    max: 3,
                  },
                  {
                    name: "achievements",
                    label: "Izpostavljeni dosežki — izberi 2 ali 3",
                    widget: "relation",
                    collection: "achievements",
                    search_fields: ["title"],
                    value_field: "{{slug}}",
                    display_fields: ["title"],
                    multiple: true,
                    min: 2,
                    max: 3,
                  },
                  {
                    name: "projects",
                    label: "Izpostavljeni projekti — izberi 2 ali 3",
                    widget: "relation",
                    collection: "projects",
                    search_fields: ["title"],
                    value_field: "{{slug}}",
                    display_fields: ["title"],
                    multiple: true,
                    min: 2,
                    max: 3,
                  },
                ]
              }
            ]
          },
          {
            name: "heroSlides",
            label: "Diapozitivi uvodnega zaslona",
            folder: "src/content/hero-slides",
            create: true,
            slug: "{{slug}}",
            fields: [
              { name: "title",    label: "Naslov",       widget: "string" },
              { name: "subtitle", label: "Podnaslov",    widget: "text" },
              { name: "image",    label: "Slika",        widget: "image", required: false },
              { name: "order", label: "Vrstni red", widget: "number", required: true, min: 1, default: 1 },
            ],
          },
        ],
      },
    }),
  ],
});
